### ISSUE TITLE
Readme - Target Deployment Version for SparkSDK 1.1

### ISSUE THREAD

**Issue by barrasso** [ciscospark/spark-ios-sdk#15]
After updating to Xcode version 8.2, I was unable to build projects using the new SparkSDK. This is because the current installation steps had instructed me to set the platform ios version set to 8.0.   This resulted in many syntax and linker errors when using the latest version of Xcode. 

To solve the problem:
1.) I updated Xcode and the Cocoapods gem to the latest versions.  
2.) I changed the Xcode project's deployment target to 9.0.
3.) I changed the Podfile to include:  `platform :ios, '9.0'`, rather than 8.0.  
Finally, I was able to pod install the correct versions and then I successfully build the project using the Spark 1.1 SDK.  

Versions:
Cocoa pods (1.1.1)
macOS Sierra (10.12.2)
Xcode (8.2 (8C38)) (target iOS version set to 9.0)

**Comment by kliu** [comment]
Fixed in v1.2
