### ISSUE TITLE
Call state problem when hanging up early

### ISSUE THREAD

**Issue by asynchrony-ringo** [ciscospark/spark-ios-sdk#17]
Description: The application crashes when hanging up too quickly on an outgoing call

Reproduction: Make an outgoing call, but hang up before the initial service call to the server is complete.

Expected: The call is logically "hung up" and responds to the eventual server response by sending a new service call to terminate the call. In the case the first service call failed and the call never ended up being created in the first place, no call need be made afterward. In either case the hangup completion handler is not called until all service calls are completed.

Actual: The Call assumes a participant URL is already available, force-unwraps it and crashes

Note: The pull request #16 improves on this by immediately returning a "failure" to hang up, but that is not the ultimate desired behavior. It's better than crashing, but not perfect.

**Comment by kliu** [comment]
Fixed in v1.2
