### ISSUE TITLE
Race condition while setting up device registration

### ISSUE THREAD

**Issue by asynchrony-ringo** [ciscospark/spark-ios-sdk#18]
There are several classes involved in device registration and initialization of the phone. The entry point is Phone.register. It makes a service call to do the actual registration then kicks off multiple processes that begin to race against each other.

1. The WebSocketService is told to connect.
2. The active calls are retrieved from the CallClient through the CallManager.
3. When the WebSocketService finally connects, then a) the reachability service is kicked off to collect Reachability data and b) new CallInfo begins to flow in to the WebSocketService
4. CallManager will process CallInfo from both the active calls returned from the service call from (2) or from (3b) then it will interact in complex ways, sometimes needing the Reachability (3a) which may not have completed.

The entire process of registering the device, starting the web socket, and obtaining reachability information should probably take place completely before any processing of CallInfo objects from either the web socket or the service. Those can still take in the data, but should pass it through to a stateful model (probably a refactored version of the CallManager/Phone) than can manage the processing of those only when it makes sense to do so. This would also be a good place to manage concepts of disconnects and reregistration.

**Comment by kliu** [comment]
Fixed in v1.2
