### ISSUE TITLE
Unable to determine if an incoming call is a video or audio call

### ISSUE THREAD

**Issue by asynchrony-ringo** [ciscospark/spark-ios-sdk#19]
It would be useful if the video/audio settings of an incoming call were accessible through the Call class. The video/audio settings are available internally through CallInfo, but that information isn't making it out of the SDK to the consumer. There are three existing variables called sendingVideo, receivingVideo, and remoteSendingVideo in the Call class. It's a little unclear the difference between remoteSendingVideo and receivingVideo as they seem like very close concepts. In either case, however, they provide the wrong information at the entry point CallObserver.callIncoming(_ call: Call). Even when the other party has an audio-only call, all of those properties return 'true', which clearly makes no sense.

Note that the CallObserver is on the 'jwt' branch, and this used to be on the PhoneObserver in master.

We see the information is available under the other participant/status as videoStatus, which will be SENDRECV if there is video and INACTIVE if there is not.

**Comment by kliu** [comment]
Fixed in v1.2
