### ISSUE TITLE
Answering a call on two devices at the same time causes problems

### ISSUE THREAD

**Issue by asynchrony-ringo** [ciscospark/spark-ios-sdk#20]
**Steps to reproduce**:

1. Log in with the same user on two different devices with fresh installs. 
2. Log in with a second user on a third device. 
3. Go to the incoming call screen on the first two devices. 
4. Call the first user with the third device.
5. Answer the call at the same time on the first two devices.

*Result on Master branch*: One of the devices crashes and the other starts a normal call.

*Result on JWT branch*: Either all three devices will end up in a call or two devices will go into a call and the third will hang up. Either way, future calls from the third device to the first two devices will fail until all three devices concurrently log out of Spark.

When the third device calls and then hangs up, it won't leave the call screen. Instead, the video from its camera will go black.

----

Our best guess is that the server is ending up with corrupted call information and not refreshing it until everyone logs out.

_Evidence to that effect_: If you log in on new devices as the same users, those devices end up in the same broken state.

_Steps to reproduce the evidence_:
If the state is broken as above, and you log in as the first user on a fourth device and the second user on a fifth device, the fifth device still can't call the fourth device. They're in that same broken state.

**Comment by kliu** [comment]
Fixed in v1.2
