### ISSUE TITLE
Phone.requestVideoCodecActivation fails if the phone is not registered

### ISSUE THREAD

**Issue by asynchrony-ringo** [ciscospark/spark-ios-sdk#21]
When the user confirms their acceptance of the video codec, a call is made that requires a URL only obtained through the phone registration. If the phone is not registered by that time, it crashes. If the registration of the phone and the activation of the video codec are called at the same time, then a race condition exists in which the app crashes if the user accepts too quickly.

**Comment by kliu** [comment]
Fixed in v1.2
