### ISSUE TITLE
Change "Link to Spark" title

### ISSUE THREAD

**Issue by NickolaySheika** [ciscospark/spark-ios-sdk#69]
Hi, as Spark is now called Webex can this screen's title be changed? 

https://github.com/webex/spark-ios-sdk/blob/ef3757f157a944a97ede33336e84ae19a8ad6485/Source/Auth/OAuthViewController.swift#L54

**Comment by olivierproffit** [comment]
@hawk-ukr the iOS SDK has been rebranded several months ago here: https://github.com/webex/webex-ios-sdk
